apiVersion: v1
kind: Template
metadata:
  name: gitlab-runner-template
parameters:
- name: GITLAB_TOKEN
  description: Token from Gitlab runner config after registration
  required: true
objects:
- apiVersion: v1
  kind: Secret
  metadata:
      name: gitlab-runner
      namespace: gitlab-runners
  stringData:
      config.toml: |
          # can up this if you have enough quota
          concurrent = 9
          listen_address = ":9252"

          [[runners]]
          name = "OpenShift Gitlab Runner"
          url = "https://gitlab.yourdomain.com/"
          token = "${GITLAB_TOKEN}"
          tls-ca-file = "/etc/gitlab-runner/certs/gitlab.yourdomain.com.crt"
          builds_dir = "/tmp"
          environment = ["HOME=/tmp"]
          executor = "kubernetes"
          [runners.kubernetes]
          namespace = "gitlab-runners"
          image = "busybox"
          helper_cpu_limit = "250m"
          helper_memory_limit = "500M"
          service_cpu_limit = "250m"
          pull_policy = "always"

          [[runners.kubernetes.volumes.secret]]
            name = "gitlab-runner-certs"
            mount_path = "/tmp/certs/"
            read_only = true
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: gitlab-runner
    namespace: gitlab
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: gitlab-runner
      spec:
        containers:
        - args:
          - --debug
          - run
          - -c
          - /etc/gitlab-runner/config.toml
          resources:
            limits:
              memory: 250Mi
              cpu: 0.25
          livenessProbe:
            httpGet:
              path: /metrics
              port: 9252
            timeoutSeconds: 1
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 1
          image: gitlab/gitlab-runner:latest
          imagePullPolicy: Always
          name: gitlab-runner
          volumeMounts:
          - mountPath: /etc/gitlab-runner
            name: config
          - mountPath: /etc/gitlab-runner/certs
            name: certs
        restartPolicy: Always
        volumes:
        - secret:
            secretName: gitlab-runner
          name: config
        - secret:
            secretName: gitlab-runner-certs
          name: certs
